name: "Update contributors"

on:
  schedule:
    - cron: '* * */7 * *'

permissions:
  contents: write
  issues: write

jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - uses: akhilmhdh/contributors-readme-action@v2.3.6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          image_size: 64
          use_username: true